INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bulgaria', 'BG', 'BGN', 1.9558);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Romania', 'RO', 'RON', 4.8431);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Northern Macedonia', 'MK', 'MKD', 62.45);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Serbia', 'RS', 'RSD', 120);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Turkey', 'TR', 'TRY', 7.5979);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('New Zealand', 'NZ', 'NZD', 1.7705);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Cook Islands', 'CK', 'NZD', 1.7705);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Niue', 'NU', 'NZD', 1.7705);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Pitcairn', 'PN', 'NZD', 1.7705);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Tokelau', 'TK', 'NZD', 1.7705);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Australian', 'AU', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Christmas Island', 'CX', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Cocos (Keeling) Islands', 'CC', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Heard and Mc Donald Islands', 'HM', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Kiribati', 'KI', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Nauru', 'NR', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Norfolk Island', 'NF', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Tuvalu', 'TV', 'AUD', 1.6598);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('American Samoa', 'AS', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Andorra', 'AD', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Austria', 'AT', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Belgium', 'BE', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Finland', 'FI', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('France', 'FR', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('French Guiana', 'GF', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('French Southern Territories', 'TF', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Germany', 'DE', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Guadeloupe', 'GP', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Ireland', 'IE', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Italy', 'IT', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Luxembourg', 'LU', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Martinique', 'MQ', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Mayotte', 'YT', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Monaco', 'MC', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Netherlands', 'NL', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Portugal', 'PT', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Reunion', 'RE', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Samoa', 'WS', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('San Marino', 'SM', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Slovenia', 'SI', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Spain', 'ES', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Vatican City State (Holy See)', 'VA', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'GBP', 0.86905);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('United Kingdom', 'GB', 'GBP', 0.86905);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Jersey', 'JE', 'GBP', 0.86905);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('British Indian Ocean Territory', 'IO', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Guam', 'GU', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Marshall Islands', 'MH', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Micronesia Federated States of', 'FM', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Northern Mariana Islands', 'MP', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Palau', 'PW', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Puerto Rico', 'PR', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Turks and Caicos Islands', 'TC', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('United States', 'US', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('United States Minor Outlying Islands', 'UM', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Virgin Islands (British)', 'VG', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Virgin Islands (US)', 'VI', 'USD', 1.0876);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Hong Kong', 'HK', 'HKD', 8.43);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Canada', 'CA', 'CAD', 1.5077);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Japan', 'JP', 'JPY', 115.87);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Afghanistan', 'AF', 'AFN', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Albania', 'AL', 'ALL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Algeria', 'DZ', 'DZD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Anguilla', 'AI', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Antigua and Barbuda', 'AG', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Dominica', 'DM', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Grenada', 'GD', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Montserrat', 'MS', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Saint Kitts', 'KN', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Saint Lucia', 'LC', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Saint Vincent Grenadines', 'VC', 'XCD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Argentina', 'AR', 'ARS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Armenia', 'AM', 'AMD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Aruba', 'AW', 'ANG', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Netherlands Antilles', 'AN', 'ANG', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Azerbaijan', 'AZ', 'AZN', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bahamas', 'BS', 'BSD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bahrain', 'BH', 'BHD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bangladesh', 'BD', 'BDT', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Barbados', 'BB', 'BBD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Belarus', 'BY', 'BYR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Belize', 'BZ', 'BZD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Benin', 'BJ', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Burkina Faso', 'BF', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Guinea-Bissau', 'GW', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Ivory Coast', 'CI', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Mali', 'ML', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Niger', 'NE', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Senegal', 'SN', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Togo', 'TG', 'XOF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bermuda', 'BM', 'BMD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bhutan', 'BT', 'INR', 81.6108);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('India', 'IN', 'INR', 81.6108);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bolivia', 'BO', 'BOB', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Botswana', 'BW', 'BWP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Bouvet Island', 'BV', 'NOK', 11.184);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Norway', 'NO', 'NOK', 11.184);
INSERT INTO countries.country(name, code, currency, rate) VALUES ('Svalbard and Jan Mayen Islands', 'SJ', 'NOK', 11.184);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Brazil', 'BR', 'BRL', 5.8565);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Brunei Darussalam', 'BN', 'BND', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Burundi', 'BI', 'BIF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Cambodia', 'KH', 'KHR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Cameroon', 'CM', 'XAF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Central African Republic', 'CF', 'XAF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Chad', 'TD', 'XAF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Congo Republic of the Democratic', 'CG', 'XAF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Equatorial Guinea', 'GQ', 'XAF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Gabon', 'GA', 'XAF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Cape Verde', 'CV', 'CVE', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Cayman Islands', 'KY', 'KYD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Chile', 'CL', 'CLP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'China', 'CN', 'CNY', 7.6665);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Colombia', 'CO', 'COP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Comoros', 'KM', 'KMF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Congo-Brazzaville', 'CD', 'CDF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Costa Rica', 'CR', 'CRC', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Croatia (Hrvatska)', 'HR', 'HRK', 7.579);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Cuba', 'CU', 'CUP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Cyprus', 'CY', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Czech Republic', 'CZ', 'CZK', 27.097);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Denmark', 'DK', 'DKK', 7.4584);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Faroe Islands', 'FO', 'DKK', 7.4584);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Greenland', 'GL', 'DKK', 7.4584);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Djibouti', 'DJ', 'DJF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Dominican Republic', 'DO', 'DOP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'East Timor', 'TP', 'IDR', 16178.05);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Indonesia', 'ID', 'IDR', 16178.05);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Ecuador', 'EC', 'ECS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Egypt', 'EG', 'EGP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'El Salvador', 'SV', 'SVC', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Eritrea', 'ER', 'ETB', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Ethiopia', 'ET', 'ETB', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Estonia', 'EE', 'EEK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Falkland Islands (Malvinas)', 'FK', 'FKP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Fiji', 'FJ', 'FJD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'French Polynesia', 'PF', 'XPF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'New Caledonia', 'NC', 'XPF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Wallis and Futuna Islands', 'WF', 'XPF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Gambia', 'GM', 'GMD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Georgia', 'GE', 'GEL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Gibraltar', 'GI', 'GIP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Guatemala', 'GT', 'GTQ', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Guinea', 'GN', 'GNF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Guyana', 'GY', 'GYD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Haiti', 'HT', 'HTG', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Honduras', 'HN', 'HNL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Hungary', 'HU', 'HUF', 352.72);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Iceland', 'IS', 'ISK', 159.3);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Iran (Islamic Republic of)', 'IR', 'IRR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Iraq', 'IQ', 'IQD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Israel', 'IL', 'ILS', 3.8069);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Jamaica', 'JM', 'JMD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Jordan', 'JO', 'JOD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Kazakhstan', 'KZ', 'KZT', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Kenya', 'KE', 'KES', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Korea North', 'KP', 'KPW', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Korea South', 'KR', 'KRW', 1313.09);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Kuwait', 'KW', 'KWD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Kyrgyzstan', 'KG', 'KGS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Lao People?s Democratic Republic', 'LA', 'LAK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Latvia', 'LV', 'LVL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Lebanon', 'LB', 'LBP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Lesotho', 'LS', 'LSL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Liberia', 'LR', 'LRD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Libyan Arab Jamahiriya', 'LY', 'LYD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Liechtenstein', 'LI', 'CHF', 1.0558);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Switzerland', 'CH', 'CHF', 1.0558);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Lithuania', 'LT', 'LTL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Macau', 'MO', 'MOP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Madagascar', 'MG', 'MGA', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Malawi', 'MW', 'MWK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Malaysia', 'MY', 'MYR', 4.6767);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Maldives', 'MV', 'MVR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Malta', 'MT', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Mauritania', 'MR', 'MRO', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Mauritius', 'MU', 'MUR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Mexico', 'MX', 'MXN', 25.7953);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Moldova Republic of', 'MD', 'MDL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Mongolia', 'MN', 'MNT', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Morocco', 'MA', 'MAD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Western Sahara', 'EH', 'MAD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Mozambique', 'MZ', 'MZN', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Myanmar', 'MM', 'MMK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Namibia', 'NA', 'NAD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Nepal', 'NP', 'NPR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Nicaragua', 'NI', 'NIO', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Nigeria', 'NG', 'NGN', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Oman', 'OM', 'OMR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Pakistan', 'PK', 'PKR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Panama', 'PA', 'PAB', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Papua New Guinea', 'PG', 'PGK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Paraguay', 'PY', 'PYG', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Peru', 'PE', 'PEN', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Philippines', 'PH', 'PHP', 54.772);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Poland', 'PL', 'PLN', 4.5336);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Qatar', 'QA', 'QAR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Russian Federation', 'RU', 'RUB', 79.892);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Rwanda', 'RW', 'RWF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Sao Tome and Principe', 'ST', 'STD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Saudi Arabia', 'SA', 'SAR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Seychelles', 'SC', 'SCR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Sierra Leone', 'SL', 'SLL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Singapore', 'SG', 'SGD', 1.5324);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Slovakia (Slovak Republic)', 'SK', 'SKK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Solomon Islands', 'SB', 'SBD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Somalia', 'SO', 'SOS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'South Africa', 'ZA', 'ZAR', 19.6572);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Sri Lanka', 'LK', 'LKR', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Sudan', 'SD', 'SDG', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Suriname', 'SR', 'SRD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Swaziland', 'SZ', 'SZL', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Sweden', 'SE', 'SEK', 10.6639);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Syrian Arab Republic', 'SY', 'SYP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Taiwan', 'TW', 'TWD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Tajikistan', 'TJ', 'TJS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Tanzania', 'TZ', 'TZS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Thailand', 'TH', 'THB', 35.216);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Tonga', 'TO', 'TOP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Trinidad and Tobago', 'TT', 'TTD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Tunisia', 'TN', 'TND', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Turkmenistan', 'TM', 'TMT', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Uganda', 'UG', 'UGX', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Ukraine', 'UA', 'UAH', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'United Arab Emirates', 'AE', 'AED', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Uruguay', 'UY', 'UYU', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Uzbekistan', 'UZ', 'UZS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Vanuatu', 'VU', 'VUV', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Venezuela', 'VE', 'VEF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Vietnam', 'VN', 'VND', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Yemen', 'YE', 'YER', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Zambia', 'ZM', 'ZMK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Zimbabwe', 'ZW', 'ZWD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Aland Islands', 'AX', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Angola', 'AO', 'AOA', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Antarctica', 'AQ', 'AQD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Bosnia and Herzegovina', 'BA', 'BAM', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Congo (Kinshasa)', 'CD', 'CDF', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Ghana', 'GH', 'GHS', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Guernsey', 'GG', 'GGP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Isle of Man', 'IM', 'GBP', 0.86905);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Laos', 'LA', 'LAK', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Macao S.A.R.', 'MO', 'MOP', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Montenegro', 'ME', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Palestinian Territory', 'PS', 'JOD', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Saint Barthelemy', 'BL', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Saint Helena', 'SH', 'GBP', 0.86905);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Saint Martin (French part)', 'MF', 'ANG', null);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'Saint Pierre and Miquelon', 'PM', 'EUR', 1);
INSERT INTO countries.country(name, code, currency, rate) VALUES ( 'USed Forces', 'USAF', 'USD', 1.0876);
